# Generated by Django 4.1.7 on 2023-05-10 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_category_listing_categorylist1'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlisting', to=settings.AUTH_USER_MODEL),
        ),
    ]
